
/* Drop Tables */

DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
DROP TABLE POST CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE ADDRESS
(
	AD_ID NUMBER(5) NOT NULL,
	ME_ID VARCHAR2(20) NOT NULL,
	AD_RECIPIENT VARCHAR2(40) NOT NULL,
	AD_TEL VARCHAR2(11) NOT NULL,
	AD_ZIPCODE NUMBER(5) NOT NULL,
	AD_MAIN VARCHAR2(500) NOT NULL,
	AD_DETAIL VARCHAR2(500) NOT NULL,
	AD_CONDITION NUMBER(1) NOT NULL,
	PRIMARY KEY (AD_ID)
);


CREATE TABLE BOARD
(
	BO_ID NUMBER(5) NOT NULL,
	IT_ID NUMBER(5),
	BO_NAME VARCHAR2(100),
	PRIMARY KEY (BO_ID)
);


CREATE TABLE CART
(
	CA_ID NUMBER(6) NOT NULL,
	ME_ID VARCHAR2(20) NOT NULL,
	IT_ID NUMBER(5) NOT NULL,
	CA_AMOUNT NUMBER(3) NOT NULL,
	CA_REGDATE TIMESTAMP NOT NULL,
	CA_CONDITION NUMBER(1) DEFAULT 0 NOT NULL,
	PRIMARY KEY (CA_ID)
);


CREATE TABLE CATEGORIES
(
	CG_ID NUMBER(1) NOT NULL,
	CG_NAME VARCHAR2(100) NOT NULL,
	PRIMARY KEY (CG_ID)
);


CREATE TABLE ITEM
(
	IT_ID NUMBER(5) NOT NULL,
	CG_ID NUMBER(1) NOT NULL,
	IT_NAME VARCHAR2(100) NOT NULL,
	IT_COMPANY VARCHAR2(50) NOT NULL,
	IT_SMALL_IMG VARCHAR2(100) NOT NULL,
	IT_LARGE_IMG VARCHAR2(100) NOT NULL,
	IT_DETAIL_IMG VARCHAR2(100) NOT NULL,
	IT_REGDATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
	IT_INFO VARCHAR2(4000) NOT NULL,
	IT_STOCK NUMBER(3) NOT NULL,
	IT_COST NUMBER(8) NOT NULL,
	IT_PRICE NUMBER(8) NOT NULL,
	IT_GRADE NUMBER(1,2),
	PRIMARY KEY (IT_ID)
);


CREATE TABLE MEMBERS
(
	ME_ID VARCHAR2(20) NOT NULL,
	ME_PW VARCHAR2(1000) NOT NULL,
	ME_NAME VARCHAR2(40) NOT NULL,
	ME_EMAIL VARCHAR2(60) NOT NULL,
	ME_MOBILE VARCHAR2(11) NOT NULL,
	ME_REGDATE TIMESTAMP NOT NULL,
	ME_AUTHORITY VARCHAR2(50) DEFAULT 'role_user' NOT NULL,
	ME_ENABLED NUMBER(1) NOT NULL,
	ME_CONDITION NUMBER(1) DEFAULT 0 NOT NULL,
	ME_KEY VARCHAR2(30) UNIQUE,
	PRIMARY KEY (ME_ID)
);


CREATE TABLE ORDERS
(
	OD_ID NUMBER(7) NOT NULL,
	AD_ID NUMBER(5) NOT NULL,
	ME_ID VARCHAR2(20) NOT NULL,
	IT_ID NUMBER(5) NOT NULL,
	OD_CONDITION NUMBER(1) DEFAULT 1 NOT NULL,
	OD_QUANTITY NUMBER(3) NOT NULL,
	OD_REGDATE TIMESTAMP NOT NULL,
	PRIMARY KEY (OD_ID)
);


CREATE TABLE POST
(
	PO_NUM NUMBER(6) NOT NULL,
	ME_ID VARCHAR2(20) NOT NULL,
	BO_ID NUMBER(5) NOT NULL,
	PO_WRITER VARCHAR2(60) NOT NULL,
	PO_TITLE VARCHAR2(80) NOT NULL,
	PO_CONTENT VARCHAR2(4000) NOT NULL,
	PO_REGDATE TIMESTAMP NOT NULL,
	PO_HIT NUMBER(6) DEFAULT 0 NOT NULL,
	PO_REF NUMBER(2) DEFAULT 0,
	PO_REF_LEVEL NUMBER(3) DEFAULT 0,
	PO_REF_STEP NUMBER(3) DEFAULT 0,
	WRITER_IP VARCHAR2(15) NOT NULL,
	PO_CONDITION NUMBER(1) DEFAULT 0 NOT NULL,
	PRIMARY KEY (PO_NUM)
);



/* Create Foreign Keys */

ALTER TABLE ORDERS
	ADD FOREIGN KEY (AD_ID)
	REFERENCES ADDRESS (AD_ID)
;


ALTER TABLE POST
	ADD FOREIGN KEY (BO_ID)
	REFERENCES BOARD (BO_ID)
;


ALTER TABLE ITEM
	ADD FOREIGN KEY (CG_ID)
	REFERENCES CATEGORIES (CG_ID)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (IT_ID)
	REFERENCES ITEM (IT_ID)
;


ALTER TABLE CART
	ADD FOREIGN KEY (IT_ID)
	REFERENCES ITEM (IT_ID)
;


ALTER TABLE ORDERS
	ADD FOREIGN KEY (IT_ID)
	REFERENCES ITEM (IT_ID)
;


ALTER TABLE ADDRESS
	ADD FOREIGN KEY (ME_ID)
	REFERENCES MEMBERS (ME_ID)
;


ALTER TABLE CART
	ADD FOREIGN KEY (ME_ID)
	REFERENCES MEMBERS (ME_ID)
;


ALTER TABLE ORDERS
	ADD FOREIGN KEY (ME_ID)
	REFERENCES MEMBERS (ME_ID)
;


ALTER TABLE POST
	ADD FOREIGN KEY (ME_ID)
	REFERENCES MEMBERS (ME_ID)
;



